"""Stub file for custom_components/reflex_react_github_calendar/github_calendar.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex.components.component import NoSSRComponent

REACT_GITHUB_CALENDAR_VERSION = "react-github-calendar@5.0.6"

class GitHubCalendar(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        include_tooltip_styles: bool | None = False,
        username: Var[str] | str | None = None,
        year: Var[int | str] | int | str | None = None,
        error_message: Var[str] | str | None = None,
        throw_on_error: Var[bool] | bool | None = None,
        block_margin: Var[int] | int | None = None,
        block_radius: Var[int] | int | None = None,
        block_size: Var[int] | int | None = None,
        color_scheme: Var[str] | str | None = None,
        font_size: Var[int] | int | None = None,
        labels: Var[dict[str, Any]] | dict[str, Any] | None = None,
        max_level: Var[int] | int | None = None,
        min_level: Var[int] | int | None = None,
        loading: Var[bool] | bool | None = None,
        show_color_legend: Var[bool] | bool | None = None,
        show_month_labels: Var[bool] | bool | None = None,
        show_total_count: Var[bool] | bool | None = None,
        show_weekday_labels: Var[bool | list[str]] | bool | list[str] | None = None,
        theme: Var[dict[str, Any]] | dict[str, Any] | None = None,
        week_start: Var[int] | int | None = None,
        transform_data: Any | Var[Any] | None = None,
        render_block: Any | Var[Any] | None = None,
        render_color_legend: Any | Var[Any] | None = None,
        tooltips: Var[dict[str, Any]] | dict[str, Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "GitHubCalendar":
        """Create the component, optionally importing the tooltip stylesheet.

        v5 tooltips are headless (ADR-7), so the bundled stylesheet is opt-in.
        Pass ``include_tooltip_styles=True`` to emit
        ``import "react-github-calendar/tooltips.css";`` once in the frontend."""
        ...

github_calendar = GitHubCalendar.create
